services:
  docs:
    image: agent_chat_app_local_docs
    container_name: agent_chat_app_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./agent_chat_app:/app/agent_chat_app:z
    ports:
      - '9000:9000'
    command: /start-docs
