# Generated by Django 5.1.11 on 2025-08-23 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_document_documentchunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_model', models.CharField(default='gemma2:2b', max_length=100)),
                ('system_instruction', models.TextField(default='You are a helpful AI assistant. Be concise and accurate in your responses.', help_text='Custom system instruction/prompt for the AI model')),
                ('max_tokens', models.IntegerField(default=2048, help_text='Maximum tokens for response')),
                ('temperature', models.FloatField(default=0.7, help_text='Response randomness (0.0-1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
