# Generated by Django 5.1.11 on 2025-08-24 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20)),
                ('logger_name', models.CharField(db_index=True, max_length=200)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, max_length=200)),
                ('function', models.CharField(blank=True, max_length=200)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('thread_id', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'level'], name='logviewer_l_timesta_a30397_idx'), models.Index(fields=['logger_name', '-timestamp'], name='logviewer_l_logger__44b142_idx')],
            },
        ),
    ]
