# Generated by Django 5.1.11 on 2025-08-24 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='receipts.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipts.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='receipts.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, default='', max_length=200)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('PLN', 'Polish Złoty'), ('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound')], default='PLN', max_length=3)),
                ('receipt_file', models.FileField(upload_to='receipt_files/')),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('raw_text', models.JSONField(blank=True, default=dict)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('processing', 'W trakcie przetwarzania'), ('review_pending', 'Oczekuje na weryfikację'), ('completed', 'Zakończono'), ('error', 'Błąd')], default='pending', max_length=20)),
                ('processing_step', models.CharField(choices=[('uploaded', 'File Uploaded'), ('ocr_in_progress', 'OCR in Progress'), ('ocr_completed', 'OCR Completed'), ('parsing_in_progress', 'Parsing in Progress'), ('parsing_completed', 'Parsing Completed'), ('matching_in_progress', 'Matching Products'), ('matching_completed', 'Matching Completed'), ('finalizing_inventory', 'Finalizing Inventory'), ('review_pending', 'Review Pending'), ('done', 'Done'), ('failed', 'Failed')], default='uploaded', max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('purchase', 'Purchase'), ('consumption', 'Consumption'), ('adjustment', 'Manual Adjustment'), ('expired', 'Expired')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=3, max_digits=10)),
                ('new_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='receipts.inventoryitem')),
                ('source_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipts.receipt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('match_confidence', models.FloatField(default=0.0)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('alias', 'Alias Match'), ('fuzzy', 'Fuzzy Match'), ('created', 'Created Product'), ('manual', 'Manual Match')], default='exact', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_line_items', to='receipts.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='receipts.receipt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='receipts_pr_name_b4ec5c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='receipts_pr_barcode_a8173f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='receipts_pr_is_acti_566dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'status'], name='receipts_re_user_id_12510a_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status', 'processing_step'], name='receipts_re_status_5091fc_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['created_at'], name='receipts_re_created_f612f6_idx'),
        ),
    ]
