# Generated by Django 5.1.11 on 2025-08-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='attempts_mistral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiptlineitem',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptlineitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptlineitem',
            name='unit_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
